;############################################################################################################################
; Use to build all and the output is send to the build.txt file.
; pio run >build.txt 
;
; The buildfs will build the littlefs from the data_dir
; pio run -t buildfs 
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
;############################################################################################################################

[platformio]
src_dir = ./src
data_dir = ./Littlefs

[env]
platform32 = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
platform_packages32 =
  platformio/tool-mklittlefs
  ;platformio/tool-openocd-esp32
  ;platformio/tool-esptoolpy
framework = arduino
lib_deps = 
	;wnatth3/WiFiManager@^2.0.16-rc.2
    https://github.com/tzapu/WiFiManager.git
    https://github.com/ESP32Async/ESPAsyncWebServer.git
    https://github.com/ESP32Async/ESPAsyncTCP.git

build_flags =
    -D CORE_DEBUG_LEVEL=0 
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=5000   ;// (keep default 5000)
    -D CONFIG_ASYNC_TCP_PRIORITY=10         ;// (keep default 10 )
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=16       ;// (keep default 65)
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1      ;// force async_tcp task to be on same core as Arduino app (default is any core)
    -D CONFIG_ASYNC_TCP_STACK_SIZE=8192    ;// reduce the stack size (default is 16K)
lib_compat_mode = strict
lib_ldf_mode = chain
extra_scripts = Scripts/extra_script.py
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs ; set the filesystem to LittleFS so that it will be used in the upload and build process

[env:esp12e]
platform = espressif8266
board = esp12e
lib_deps =
    ${env.lib_deps}
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-12E.local ;192.168.5.14

[env:esp32_4MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32dev
board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-ESP.local ;192.168.5.14

[env:esp32_8MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32dev
board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-ESP.local ;192.168.5.14

[env:esp32_16MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32dev
board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-ESP.local ;192.168.5.14

[env:esp32_32MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32dev
board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-ESP.local ;192.168.5.14

; WEMOS LOLIN S2 PICO
[env:esp32s2_4MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}

board = lolin_s2_pico
board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S2.local ;192.168.5.14

[env:esp32s2_8MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}

board = lolin_s2_pico
board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S2.local ;192.168.5.14

[env:esp32s2_16MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = lolin_s2_pico
board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S2.local ;192.168.5.14

[env:esp32s3_4MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-s3-devkitc-1
board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S3.local ;192.168.5.14

[env:esp32s3_8MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-s3-devkitc-1
board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
upload_flags= --auth="admin"
upload_protocol = espota
upload_port=ESP-LittleFS-S3.local ;192.168.5.14

[env:esp32s3_16MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-s3-devkitc-1
board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S3.local ;192.168.5.14

[env:esp32s3_32MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-s3-devkitc-1
board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-S3.local ;192.168.5.14

[env:esp32c3_4MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C3.local ;192.168.5.14

[env:esp32c3_8MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C3.local ;192.168.5.14

[env:esp32c3_16MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C3.local ;192.168.5.14

[env:esp32c3_32MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-c3-devkitc-02
; As i was using a https://wiki.luatos.org/chips/esp32c3/board.html that has no RS232 chip only USB
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.flash_mode = dio ; set the flash mode to as slow as posible so that it will support all board
board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C3.local ;192.168.5.14


[env:esp32c5_4MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D NO_OTA=1
board = esp32-c5-devkitc-1
board_build.partitions = partitions\no_ota_large_spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C5.local ;192.168.5.14

[env:esp32c5_8MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-c5-devkitc-1
board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C5.local ;192.168.5.14

[env:esp32c5_16MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-c5-devkitc-1
board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C5.local ;192.168.5.14

[env:esp32c5_32MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

board = esp32-c5-devkitc-1
board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C5.local ;192.168.5.14

[env:esp32c6_4MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c6_8MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c6_16MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c6_32MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c6-devkitc-1

board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c2_4MB]
; satble version  3.2.1 version 
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
board = esp32-c2-devkitm-1
build_flags = 
    ${env.build_flags}
    -D NO_OTA=1
board_build.partitions = partitions\no_ota_large_spiffs_4MB.csv
;board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304

;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-ESP.local ;192.168.5.14



[env:esp32c61_4MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c61-devkitc1-n8r2

board_build.partitions = partitions\spiffs_4MB.csv
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14



[env:esp32c61_8MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c61-devkitc1-n8r2

board_build.partitions = partitions\spiffs_8MB.csv
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c61_16MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c61-devkitc1-n8r2

board_build.partitions = partitions\spiffs_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14

[env:esp32c61_32MB]
platform = ${env.platform32}
platform_packages =${env.platform_packages32}
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
board = esp32-c61-devkitc1-n8r2

board_build.partitions = partitions\spiffs_32MB.csv
board_upload.flash_size = 32MB
board_upload.maximum_size = 33554432
;upload_flags= --auth="admin"
;upload_protocol = espota
;upload_port=ESP-LittleFS-C6.local ;192.168.5.14
